name: Build

on: push

env:
  MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Maven Build
        run: mvn $MAVEN_CLI_OPTS clean verify -Dmaven.test.skip=true