name: Selenium Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -q
          sudo apt install ./google-chrome-stable_current_amd64.deb
      - name: Maven Build
        run: mvn -B clean verify -Dmaven.test.skip=true
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Maven Test
        run: mvn -B clean test
      - name: Upload Extent Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: extent-report
          path: ./target/extent-reports/Index.html
      - name: Upload Junit Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: junit-report
          path: ./target/surefire-reports/junitreports/*.xml
  report:
    runs-on: ubuntu-latest
    needs: test
    if: success() || failure()
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: junit-report            # artifact name
          name: JUnit Tests                  # Name of the check run which will be created
          path: 'TEST-cl.gera.selenium.amzn.tests.NavbarTest.xml'                     # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results