name: Selenium Testing

on: workflow_dispatch

env:
  MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Install Google Chrome
        run: |
         wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${{ vars.CHROME_VERSION }}-1_amd64.deb -q -O google-chrome-stable_current_amd64.deb
         sudo dpkg -i google-chrome-stable_current_amd64.deb
      - name: Run Tests
        run: mvn $MAVEN_CLI_OPTS clean test
      - name: Upload Extent Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: extent-report
          path: ./target/extent-reports/*.html
  publish-report:
    needs: test
    if: success() || failure()
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: extent-report
          path: report
      - name: Save report file
        run: echo "REPORT_FILE=$(find report -name '*.html' -exec basename {} \;)" >> $GITHUB_ENV
      - name: Add content to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_branch: gh-pages
          publish_dir: report
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
          name: github-pages
          retention-days: 1
      - name: Deploy page artifact
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Add report to summary
        run: echo "Report URL -> https://${{github.repository_owner}}.github.io/${{github.event.repository.name}}/${{env.REPORT_FILE}}" >> $GITHUB_STEP_SUMMARY