name: Selenium Testing

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Install Google Chrome
        run: |
         wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -q
         sudo apt install ./google-chrome-stable_current_amd64.deb
      - name: Run Tests
        run: mvn -B clean test
      - name: Upload Extent Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: extent-report
          path: ./target/extent-reports/*.html
      - name: Generate Github Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Tests
          path: ./target/surefire-reports/junitreports/*.xml
          reporter: java-junit
          fail-on-error: false
  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: extent-report
          path: report
      - name: Add content to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_branch: gh-pages
          publish_dir: report
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
          name: github-pages
          retention-days: 1
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Add report to summary
        run: |
          echo "Report: $(echo "https://${GITHUB_USER}.github.io/$(echo $GITHUB_REPOSITORY | grep -Eio '\/(.*)' | grep -Eio '[a-z]+')")$(find report -name '*.html')" >> $GITHUB_STEP_SUMMARY